# data字段现在不再直接使用，因为训练脚本会硬编码指向train_trajectories
# 但保留它以备将来之用
data: /mnt/c/subway_surfers_ai/data/trajectories_cleaned

train_params:
  device: "cuda"
  epochs: 20
  batch_size: 32
  learning_rate: 0.0001 # 提高初始学习率
  weight_decay: 0.1
  num_workers: 8
  sequence_length: 30
  action_resample_window: 15
  random_interval: 3
  label_smoothing: 0.1 # 新增标签平滑

model_params:
  state_dim: 8
  act_dim: 5
  n_embd: 128
  n_head: 4
  n_layer: 3 # 减少层数以防过拟合
  dropout: 0.1
  block_size: 90
  max_timestep: 40000